language: generic
services: 
  - docker
after_success: 
  - "docker build -t kriley17/user-wishlist ."
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_ID\" --password-stdin"
  - "docker push kriley17/user-wishlist"
deploy: 
  access_key_id: $AWS_ACCESS_KEY
  app: kyle-wishlist-app
  bucket_name: multi-cont-wish-app-kyle
  bucket_path: docker
  env: Kylewishlistapp-env
  provider: elasticbeanstalk
  region: us-east-1
  secret_access_key: $AWS_SECRET_KEY
  true: 
    branch: multi-cont-app